# Generated by Django 4.2.4 on 2024-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetarium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consejero',
            fields=[
                ('id_consejero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225)),
                ('apellido', models.CharField(max_length=225)),
                ('edad', models.IntegerField()),
                ('idioma', models.CharField(max_length=225)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('titulacion', models.CharField(max_length=225)),
                ('pais', models.TextField()),
                ('experiencia', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'tbl_consejeros',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('ingredientes', models.CharField(max_length=225)),
                ('descripcion', models.CharField(max_length=255)),
                ('tiempo_preparacion', models.CharField(max_length=10)),
                ('dificultad', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_recetas',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
