# Generated by Django 5.0.6 on 2024-06-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recetarium', '0003_licencia_rol_consejero_descripcion_and_more'),
    ]

    operations = [
    ]
