# Generated by Django 5.0.6 on 2024-06-26 05:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetarium', '0005_alter_user_options_alter_user_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='id',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='fecha_registro_ingredientes',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 26, 5, 38, 4, 605308, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='id_ingrediente',
            field=models.AutoField(default='timezone.now()', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consejero',
            name='descripcion',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='consejero',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='receta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recetarium.receta'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Licencia',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
